### ISSUE TITLE
Spree::Gateway::Bogus is deprecated. Please use Spree::PaymentMethod::BogusCreditCard instead

### ISSUE THREAD

**Issue by DanielePalombo** [nebulab/rubocop-solidus#26]
https://github.com/nebulab/rubocop-solidus/pull/7

Deprecation PR: https://github.com/solidusio/solidus/pull/2001

solidus minimum version: 2.10

because of https://github.com/solidusio/solidus/commit/d1082aff1b98d7aff4825f8a55cb4f4b567b45c0

**Comment by MassimilianoLattanzio** [comment]
Added minimum Solidus version in #43
