### ISSUE TITLE
Remove reimbursement_success_hooks and reimbursement_failed_hooks

### ISSUE THREAD

**Issue by DanielePalombo** [nebulab/rubocop-solidus#27]
Detect reimbursement_success_hooks and reimbursement_failed_hooks

https://github.com/nebulab/rubocop-solidus/pull/9

solidus minimum version: 2.11

Deprecation Pr: https://github.com/solidusio/solidus/pull/3541

**Comment by MassimilianoLattanzio** [comment]
Added minimum Solidus version in #43
