### ISSUE TITLE
Stop calling Spree::Refund#perform! after creating a refund

### ISSUE THREAD

**Issue by DanielePalombo** [nebulab/rubocop-solidus#28]
From Solidus v3.0 onwards, #perform! will need to be explicitly called when creating new refunds. Please, change your code from:

Spree::Refund.create(your: attributes)

to:

Spree::Refund.create(your: attributes, perform_after_creation: false).perform!

The perform_after_creation attribute will be removed in Solidus 3.x.

Stop calling perform! as Spree::Refund after_create callback [#3641](https://github.com/solidusio/solidus/pull/3641) ([kennyadsl](https://github.com/kennyadsl))

Look for:

For solidus 2.11 looks for Spree::Refund.create/new without perform_after_create

----

For Solidus < 2.11 we can consider patching the model by overriding the method as done here:

https://github.com/solidusio/solidus/pull/3641/commits/3d6f51095c2b3868f880ca06c51345bc0a5a7331

solidus_minimum_version: 2.11

**Comment by DanielePalombo** [comment]
The merged PR is https://github.com/nebulab/rubocop-solidus/pull/11.

I discussed it with @piyushswain and @michellecrisologo, but I don't think it will be ok, because the perform! method is automatically executed when the Refund is created. If someone installs rubocop-solidus on a previous solidus version it will autocorrect it, calling the method twice.

**Comment by DanielePalombo** [comment]
Will need to research how to do the version checks on Rails/Solidus so that this won't run if the version is not correct.

**Comment by DanielePalombo** [comment]
we have to set the solidus minimum version on the cop

**Comment by MassimilianoLattanzio** [comment]
Added minimum Solidus version in #43
