### ISSUE TITLE
Targeted Solidus Version

### ISSUE THREAD

**Issue by DanielePalombo** [nebulab/rubocop-solidus#34]
Add a feature that allows cops to check and decide whether to execute themselves against a solidus version mentioned in the configuration.

rubocop.yml can hold a solidus version. e.g. - TargetSolidusVersion in the configuration.

AllCops:
  TargetSolidusVersion: 2.11

There should a module that holds methods that allow us to

assign a minimum solidus version to a cop

fetch the TargetSolidusVersion from the rubocop.yml file

check a cops minimum version against the targeted version and allow a cop to be skipped.

Note: Check minimum_target_rails_version method on rubocop-rails for an idea on the implementation

Issue will be closed when:

- [ ] User can set a TargetSolidusVersion from rubocop.yml
- [ ] User can set a minimum supported version of solidus for a cop
- [ ] Cop is skipped if target solidus version is lower than minimum supported version of the cop.

**Comment by DanielePalombo** [comment]
This is on review, right?

**Comment by MassimilianoLattanzio** [comment]
> This is on review, right?

Yeah, right
